#!/usr/bin/env python3
"""Build a compact Markdown fact archive from a xuanxue JSON report."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a human-readable fact archive from combo/module JSON.")
    parser.add_argument("input_json", help="Combo or module JSON generated by xuanxue_console.py.")
    parser.add_argument("--output", required=True, help="Markdown archive path, usually <RUN_DIR>/data/<case>-facts.md.")
    parser.add_argument("--manifest", help="Optional case_manifest.json to update with artifacts.fact_archive_markdown.")
    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def as_text(value: Any, default: str = "待补") -> str:
    if value is None or value == "":
        return default
    if isinstance(value, (list, tuple)):
        return "、".join(as_text(item, default="") for item in value if item not in (None, ""))
    return str(value)


def table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    if not rows:
        return []
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(as_text(item, "") for item in row) + " |")
    return lines


def report_modules(report: dict[str, Any]) -> list[dict[str, Any]]:
    if report.get("module") == "combo":
        modules = report.get("facts", {}).get("modules", [])
        return [item for item in modules if isinstance(item, dict)]
    return [report]


def module_map(report: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {str(item.get("module", "")): item for item in report_modules(report)}


def render_bazi(module: dict[str, Any]) -> list[str]:
    facts = module.get("facts", {})
    pillars = facts.get("pillars", {})
    flow = facts.get("flow", {})
    current_dayun = flow.get("current_dayun", {})
    profiles = facts.get("profiles", {})
    ten_gods = profiles.get("ten_gods", {}).get("combined", {})
    elements = profiles.get("elements", {}).get("stems_plus_hidden", {})
    lines = [
        "## 八字事实",
        "",
        f"- 公历生日：{as_text(facts.get('solar'))}",
        f"- 四柱：{as_text(pillars.get('year'))} / {as_text(pillars.get('month'))} / {as_text(pillars.get('day'))} / {as_text(pillars.get('hour'))}",
        f"- 日主：{as_text(facts.get('day_master'))}",
        f"- 当前大运：{as_text(current_dayun.get('gan_zhi'))}（{as_text(current_dayun.get('start_year'))}-{as_text(current_dayun.get('end_year'))}）",
        f"- 流年窗口：{as_text(flow.get('as_of'))}",
        f"- 当前流日四柱：{as_text(flow.get('pillars', {}).get('year'))} / {as_text(flow.get('pillars', {}).get('month'))} / {as_text(flow.get('pillars', {}).get('day'))}",
        f"- 十神合计：{as_text([f'{key}{value}' for key, value in ten_gods.items()])}",
        f"- 五行合计：{as_text([f'{key}{value}' for key, value in elements.items()])}",
        "",
    ]
    dayun_rows = [
        [row.get("gan_zhi"), row.get("start_year"), row.get("end_year"), row.get("ten_god_gan"), row.get("growth_by_day_master")]
        for row in facts.get("dayun", [])
        if isinstance(row, dict) and row.get("gan_zhi")
    ]
    lines.extend(table(["大运", "开始", "结束", "十神", "十二长生"], dayun_rows[:8]))
    annual_rows = [
        [row.get("year"), row.get("pillar"), row.get("dayun")]
        for row in flow.get("annual_flows", [])
        if isinstance(row, dict)
    ]
    if annual_rows:
        lines.extend(["", "### 流年序列", ""])
        lines.extend(table(["年份", "流年", "所在大运"], annual_rows))
    lines.append("")
    return lines


def render_ziwei(module: dict[str, Any]) -> list[str]:
    facts = module.get("facts", {})
    current = facts.get("current_decadal") or {}
    lines = [
        "## 紫微事实",
        "",
        f"- 命宫：{as_text(facts.get('soul_palace_branch'))}",
        f"- 身宫：{as_text(facts.get('body_palace_branch'))}",
        f"- 当前大限：{as_text(current.get('name'))}，主星：{as_text(current.get('major_stars'))}",
        "",
    ]
    palaces = [
        [item.get("name"), as_text(item.get("major_stars"))]
        for item in facts.get("palaces", [])
        if isinstance(item, dict) and item.get("name") in {"命宫", "夫妻宫", "财帛宫", "官禄宫", "福德宫"}
    ]
    lines.extend(table(["宫位", "主星"], palaces))
    mutagens = [
        [item.get("star"), item.get("mutagen"), item.get("palace")]
        for item in facts.get("year_mutagens", [])
        if isinstance(item, dict)
    ]
    if mutagens:
        lines.extend(["", "### 年四化", ""])
        lines.extend(table(["星曜", "四化", "宫位"], mutagens))
    lines.append("")
    return lines


def render_western(module: dict[str, Any]) -> list[str]:
    facts = module.get("facts", {})
    houses = facts.get("houses", {}) or {}
    angles = houses.get("angles", {}) or {}
    lines = [
        "## 西占事实",
        "",
        f"- 上升：{as_text(angles.get('ascendant', {}).get('sign'))}",
        f"- 天顶：{as_text(angles.get('midheaven', {}).get('sign'))}",
        f"- 月相：{as_text(facts.get('moon_phase', {}).get('phase'))}",
        "",
    ]
    placements = [
        [row.get("body"), row.get("sign"), row.get("longitude")]
        for row in facts.get("placements", [])
        if isinstance(row, dict)
    ]
    lines.extend(table(["行星", "星座", "黄经"], placements))
    aspects = [
        [row.get("body_a"), row.get("aspect"), row.get("body_b"), row.get("orb")]
        for row in facts.get("aspects", [])
        if isinstance(row, dict)
    ]
    if aspects:
        lines.extend(["", "### 主要相位", ""])
        lines.extend(table(["行星 A", "相位", "行星 B", "容许度"], aspects[:12]))
    lines.append("")
    return lines


def render_simple_module(title: str, module: dict[str, Any]) -> list[str]:
    facts = module.get("facts", {})
    compact = json.dumps(facts, ensure_ascii=False, indent=2)
    return [f"## {title}", "", "```json", compact, "```", ""]


def render_archive(report: dict[str, Any], input_json: Path) -> str:
    modules = module_map(report)
    module_names = [name for name in modules if name]
    lines = [
        "# 排盘事实复查档案",
        "",
        "这份文件只归档脚本事实，供复查和后续写作引用；它不是读者版解读，也不替代原始 JSON。",
        "",
        f"- JSON 源文件：`{input_json}`",
        f"- JSON schema：{as_text(report.get('schema_version'))}",
        f"- 顶层模块：{as_text(report.get('module'))}",
        f"- 已归档模块：{as_text(module_names)}",
        "",
    ]
    warnings = report.get("warnings", [])
    uncertainties = report.get("uncertainties", [])
    if warnings or uncertainties:
        lines.extend(["## 警告和不确定项", ""])
        for item in warnings:
            lines.append(f"- warning: {item}")
        for item in uncertainties:
            lines.append(f"- uncertainty: {item}")
        lines.append("")

    if "bazi" in modules:
        lines.extend(render_bazi(modules["bazi"]))
    if "ziwei" in modules:
        lines.extend(render_ziwei(modules["ziwei"]))
    if "western" in modules:
        lines.extend(render_western(modules["western"]))
    if "mbti" in modules:
        lines.extend(render_simple_module("MBTI 事实", modules["mbti"]))
    if "liuyao" in modules:
        lines.extend(render_simple_module("六爻事实", modules["liuyao"]))
    if "xiaoliuren" in modules:
        lines.extend(render_simple_module("小六壬事实", modules["xiaoliuren"]))

    lines.extend(
        [
            "## 复查约定",
            "",
            "- 后续追问先查这份 MD，再回到 JSON 做精确字段核对。",
            "- 不从本文件手算四柱、大运、星曜、宫位或流年；缺字段时重新读取 JSON 或重跑脚本。",
            "- 如果出生时间、真太阳时、经纬度或 as_of 口径变化，必须重新生成 JSON 和本档案。",
            "",
        ]
    )
    return "\n".join(lines)


def update_manifest(manifest_path: Path, input_json: Path, output: Path, report: dict[str, Any]) -> None:
    manifest = load_json(manifest_path)
    artifacts = manifest.setdefault("artifacts", {})
    if not isinstance(artifacts, dict):
        artifacts = {}
        manifest["artifacts"] = artifacts
    artifacts["fact_archive_markdown"] = str(output)
    data = artifacts.setdefault("data", {})
    if isinstance(data, dict) and report.get("module") == "combo":
        data.setdefault("combo", str(input_json))
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    input_json = Path(args.input_json).resolve()
    output = Path(args.output).resolve()
    report = load_json(input_json)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_archive(report, input_json), encoding="utf-8")
    if args.manifest:
        update_manifest(Path(args.manifest).resolve(), input_json, output, report)
    print(json.dumps({"passed": True, "markdown": str(output), "input_json": str(input_json)}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
